# Generated by Django 3.2.15 on 2022-12-15 06:17

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Время приготовления должно быть больше 1 минуты.')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=7, null=True, samples=None, unique=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
